DROP TABLE NOTICEBOARD;
DROP TABLE ADMIN;
DROP TABLE RAVG;
DROP TABLE ONEREVIEW;
DROP TABLE RESTAURANT;
DROP TABLE CCODE;
DROP TABLE FREEBOARD;
DROP TABLE MEMBER;

DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE RES_SEQ;
DROP SEQUENCE ONE_SEQ;
DROP SEQUENCE FREE_SEQ;
DROP SEQUENCE CCODE_SEQ;
DROP SEQUENCE RAVG_SEQ;

CREATE TABLE MEMBER(
    MID VARCHAR2(50) PRIMARY KEY,
    MPW VARCHAR2(50) NOT NULL,
    MNAME VARCHAR2(50) NOT NULL,
    MEMAIL VARCHAR2(50),
    MTEL VARCHAR2(50),
    MBIRTH DATE,
    MRDATE DATE DEFAULT SYSDATE
);

CREATE TABLE ADMIN(
    AID VARCHAR2(50) PRIMARY KEY,
    APW VARCHAR2(50) NOT NULL,
    ANAME VARCHAR2(50) NOT NULL
);

CREATE TABLE NOTICEBOARD(
    NNO NUMBER(6) PRIMARY KEY,
    AID VARCHAR2(50) REFERENCES ADMIN(AID) NOT NULL,
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(4000),
    NRDATE DATE DEFAULT SYSDATE NOT NULL,
    NHIT NUMBER(6) DEFAULT 0 NOT NULL
);
CREATE TABLE CCODE (
    CNO NUMBER(2) PRIMARY KEY,
    CNAME VARCHAR2(50) NOT NULL
); 

CREATE TABLE RESTAURANT (
    RNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID) NOT NULL,
    CNO NUMBER(2) REFERENCES CCODE(CNO) NOT NULL,
    RNAME VARCHAR2(100) NOT NULL,
    RCONTENT VARCHAR2(4000) NOT NULL,
    RPLACE VARCHAR2(50) NOT NULL,
    MAINIMG VARCHAR2(50) NOT NULL,-- 대표 이미지
    RTEL VARCHAR2(50),
    RMENU VARCHAR2(50) NOT NULL,
    RPRICE VARCHAR2(50) NOT NULL,
    RHIT NUMBER(6) DEFAULT 0 NOT NULL,
    RRDATE DATE DEFAULT SYSDATE NOT NULL,
    AVGHIT NUMBER(6) DEFAULT 0 NOT NULL
);

CREATE TABLE RAVG (
    ANO NUMBER(6) PRIMARY KEY,
    RNO NUMBER(6) NOT NULL,
    RATING NUMBER(1) DEFAULT 0 NOT NULL,
    FOREIGN KEY (RNO) REFERENCES RESTAURANT(RNO)
        ON DELETE CASCADE
);

CREATE TABLE ONEREVIEW (
    ONO NUMBER(6) PRIMARY KEY,
    RNO NUMBER(6) NOT NULL,
    MID VARCHAR2(50) NOT NULL,
    OCONTENT VARCHAR2(200) NOT NULL,
    ORECOMMAND NUMBER(6) DEFAULT 0 NOT NULL,
    FOREIGN KEY (RNO) REFERENCES RESTAURANT(RNO)
        ON DELETE CASCADE,
    FOREIGN KEY (MID) REFERENCES MEMBER(MID)
        ON DELETE CASCADE
);

CREATE TABLE FREEBOARD (
    FNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID) NOT NULL,
    FTITLE VARCHAR2(100) NOT NULL,
    FCONTENT VARCHAR2(4000),
    FIMAGE1 VARCHAR2(50),
    FIMAGE2 VARCHAR2(50),
    FRDATE DATE DEFAULT SYSDATE NOT NULL,
    FHIT NUMBER(6) DEFAULT 0 NOT NULL,
    FGROUP NUMBER(6) NOT NULL,
    FSTEP NUMBER(6) NOT NULL,
    FINDENT NUMBER(6) NOT NULL
);

CREATE SEQUENCE NOTICE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE RES_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ONE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE FREE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE CCODE_SEQ MAXVALUE 99 NOCACHE NOCYCLE;
CREATE SEQUENCE RAVG_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

COMMIT;

SELECT * FROM MEMBER;
SELECT * FROM RESTAURANT;
SELECT * FROM ONEREVIEW;
SELECT * FROM RAVG;
SELECT * FROM FREEBOARD;
SELECT * FROM NOTICEBOARD;
SELECT * FROM CCODE;
SELECT * FROM ADMIN;